### ISSUE TITLE
[Feature] Task list add last modified time option.

### ISSUE THREAD

**Issue by lvshaokang** [apache/streampark#1185]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Task list add last modified time option for find app

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
