### ISSUE TITLE
[BUG] 1.2.4 pre release bug list

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#1192]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

In the current version (1.2.4-dev), there are a lot of issues to fix. To release the official version 1.2.4, these bugs must be resolved. The goal of this release is to deploy flink on k8s to achieve online production-level stability and availability

----

在当前的版本中(1.2.4-dev) 发现了很多问题需要解决,要发布1.2.4正式版本,这些问题必须解决. 本次发布的目标是: deploy flink on k8s 稳定性可用性达到生产级别 

### Task list

List of problems to be solved before releasing the official version：

- [x] #1193
- [x] #1194
- [x] #1195
- [x] #1196
- [x] #1197
- [x] #1198
- [x] #1199
- [x] #1200
- [x] #1201
- [x] #1202
- [x] #1203
- [x] #1204
- [x] #1205
- [x] #1206
- [x] #1207
- [x] #1208
- [x] #1209

-----

目前面临的问题：
1. [Bug] 新镜像第一次build一定失败
2. [Bug] 1.13+版本，每启动一次导致flink-webui里多一个running-job
3. [Bug] 1.13+版本，savepoint、cancle不可用
4. [Improve] 检索操作独立出来,搜索框置顶醒目
5. Launching进去后不能回退，需要刷新页面
6. [Feature]  pod启动日志
7. [Bug] ui的状态筛选不可用
8. [Feature] on k8s的mapping功能不可用
9. [Bug] 任务已经被kill运行时长还在增加
10. [Bug] flinksql逻辑有问题，提交到k8s上，一直是不断重启的，streamx是无法删除的
11. [Bug] UDF以jar包upload上传的方式，运行时报UDF类找不到的错误
12. [Bug] UDF以jar包upload上传的方式，修改UDF逻辑之后重新upload，jar包名称不变的时候不会重新build
13. [Bug] 作业基础镜像变了之后，没有重新build和push远端仓库,本地镜像不删的情况下，新镜像有时候重新build之后没有push到远端docker仓库
14. [Bug] 任务页面增加Last modified time数据
15. [Bug] flink-home修改导致任务启动失败
16. [Bug] 同步flink-home的conf文件不生效
17. [Bug] 任务列表里的任务的task统计数不显示

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shixud** [comment]
####  the flink1.15.0 version is not supported when using the dev branch to add a flink cluster. The flink-kubernetes_2.12 jar version is 1.14.0 and the error message is not accurate.
----
#### 使用dev分支添加flink cluster时不支持flink1.15.0版本. flink-kubernetes_2.12 jar version is 1.14.0 而且错误提示也不准确.
