### ISSUE TITLE
[improve] Remove apache dependency X class

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1447]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Because of mysql's GPL/LGPL dependency.
Also the "FOSS Exception License" no longer applies [1], and even if it did, it would probably not be allowed in ASF projects where you would include GPL licensed code.
So we need to make some compliance changes to comply with apache's practices.

 1. https://www.mysql.com/about/legal/licensing/foss-exception/

### Task list

- [ ] Resolving X dependencies against Dependencies Apache
     - [x] Sort out all x-class dependencies
     - [ ] Plan to replace or delete these dependencies
- [ ] Removing strong dependencies on mysql
    - [x] flink side, jdbc connector and jdbcAsyncClient used mysql , Planned remove #1444
     - [x] Support h2 replacing mysql dependencies #1453
     - [x] support PostgreSQL storage to replace mysql dependencies #1453
    - [x] streampark's platform side metadata backend storage to remove mysql strong dependency #1462
    - [x] add h2, PostgreSQL ddl Schema #1467
    - [ ] Compatibility test of SQL syntax in different dialects

**Comment by lvshaokang** [comment]
x class follow this:
https://apache.org/legal/resolved.html#category-x

**Comment by dbwiddis** [comment]
> Also the "FOSS Exception License" no longer applies [1],

As noted by that link, It has been replaced by a broader "[Universal FOSS Exception](https://oss.oracle.com/licenses/universal-foss-exception/)" which would apply.

My understanding is that it can not be distributed, but an "optional" feature could use it if the user obtained it on their own.  See, for example, Apache Hive.

**Comment by MonsterChenzhuo** [comment]
@dbwiddis  We have received your suggestion, thanks!

**Comment by MonsterChenzhuo** [comment]
@dbwiddis  We have received your suggestion, thanks!
