### ISSUE TITLE
[Bug] 2.0.0 test issue tracking list

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#2025]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

 2.0.0 test issue tracking list

### Task list

 - #2017 
 - #2029  
 - #2030 
 - #2038
 - #2039
 - #2041
 - #2043
 - #2048 
 - #2051 
 - #2052
 - #2053 
 - #1959
 - #2054 
 - #2055
 - #2067
 - #2068

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youyangkou** [comment]
测试包scala2.11环境，flink on k8s session模式创建完，start的时候报错 ![image](https://user-images.githubusercontent.com/33364356/202120785-e256c949-20b9-4eb8-9185-2565d57e52f9.png)
![image](https://user-images.githubusercontent.com/33364356/202120972-b0daa7bf-9444-4f10-9a26-e27276da3031.png)

**Comment by muchunjin** [comment]
@wolfboys Please add this issue.
[[Bug] When the user logs in, it prompts that there is no permission](https://github.com/apache/incubator-streampark/issues/2030)

**Comment by muchunjin** [comment]
@wolfboys Please add this issue.
[[Bug] When the application is in the running state, it is not a gesture when the mouse moves to the application name](https://github.com/apache/incubator-streampark/issues/2039)

**Comment by muchunjin** [comment]
@wolfboys Please add this issue.
[[Bug] An error is reported when the mysql upgrade sql statement is executed](https://github.com/apache/incubator-streampark/issues/2048)

**Comment by wolfboys** [comment]
> @wolfboys Please add this issue. [[Bug] An error is reported when the mysql upgrade sql statement is executed](https://github.com/apache/incubator-streampark/issues/2048)

done

**Comment by muchunjin** [comment]
[[Bug] After building the project, the build time is not updated](https://github.com/apache/incubator-streampark/issues/2055)

**Comment by yebukong** [comment]
Similar problems still exist in the 2.0.0 version
[[Bug] StreamX "Session Flink Cluster" cannot view flink log ](https://github.com/apache/incubator-streampark/issues/1416)

**Comment by muchunjin** [comment]
[[Bug] Under the chrome browser, under the Flink env module, when the Flink home path is too long, the path and the back button overlap](https://github.com/apache/incubator-streampark/issues/2067)

**Comment by muchunjin** [comment]
[[Bug] On the project list page, when the mouse moves to the description of the project, the mouse is displayed as a gesture, but the click does not jump](https://github.com/apache/incubator-streampark/issues/2068)

**Comment by muchunjin** [comment]
[[Bug] When upgrading from 1.2.3 to 2.0.0, the configuration items of maven setting are incorrect](https://github.com/apache/incubator-streampark/issues/2072)

**Comment by muchunjin** [comment]
[[Bug] When stopping the application, if you want to savepoint and specify a custom savepoint path, the stop will fail](https://github.com/apache/incubator-streampark/issues/2074)

**Comment by muchunjin** [comment]
[[Bug] The copy button under the Savepoints tab of the application details page does not take effect](https://github.com/apache/incubator-streampark/issues/2081)

**Comment by muchunjin** [comment]
[[Bug] The copy function of the application does not copy the args information](https://github.com/apache/incubator-streampark/issues/2082)

**Comment by muchunjin** [comment]
[[Bug] The configured value cannot be cleared in the System Setting module](https://github.com/apache/incubator-streampark/issues/2084)

**Comment by muchunjin** [comment]
[[Bug] When creating and updating a Flink cluster and selecting the execution mode as yarn session, the value of yarn queue is not passed to the api](https://github.com/apache/incubator-streampark/issues/2090)

**Comment by muchunjin** [comment]
[[Bug] In the Flink cluster list, after clicking the stop button, the cluster stops normally, but the stop button does not change to the start button](https://github.com/apache/incubator-streampark/issues/2091)

**Comment by muchunjin** [comment]
[[Bug] In the Flink cluster list, when the update button is clicked, the api returns the options parameter, but it is not displayed on the page](https://github.com/apache/incubator-streampark/issues/2092)

**Comment by xujiangfeng001** [comment]
@wolfboys Please add this issue.
https://github.com/apache/incubator-streampark/issues/2097

**Comment by xujiangfeng001** [comment]
@wolfboys Please add this issue.
[[Bug] flink yarn session cluster stop failed](https://github.com/apache/incubator-streampark/issues/2097)
