### ISSUE TITLE
[Proposal] Support external link in Flink Application

### ISSUE THREAD

**Issue by saLeox** [apache/streampark#2216]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

**Background**:

There should be a place to hold and display the useful external link (such as Job Metrics / Savepoint root path, etc) for each Flink Job.

This feature will allow user to customise their own external link, display it as a badge inside the Flink Application detail page, and jump to other page after clicking it.

For example, I am using Grafana, the link url format will be fixed in the following way:
[https://grafana/{template_name}/flink-monitoring?var-JobId=var-JobId={job_id}](https://grafana/%7Btemplate_name%7D/flink-monitoring?var-JobId=var-JobId=%7Bjob_id%7D)

The value of place holder, job_id, can be fetched from existing meta data of Flink Job easily.

It will bring more convenience to user if they can access to the external links related to Flink inside the Streampark.

**Outcome**:

<img width="1164" alt="s1" src="https://user-images.githubusercontent.com/23732067/210077132-bab3add5-c932-426f-91f0-45e67f0315ed.png">

<img width="1188" alt="s2" src="https://user-images.githubusercontent.com/23732067/210077142-a96bd27b-fe67-4bc7-98c8-323877990ebb.png">

### Task list

- [x] #2191 
- [x] #2215

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wolfboys** [comment]
great feature, come on, we can discuss more details. Front-end developers may be required to join

**Comment by saLeox** [comment]
> great feature, come on, we can discuss more details. Front-end developers may be required to join

Thanks @wolfboys, looking forward to the coming discuss. 
We have a colleague in our team to join as a front end dev as well.
