### ISSUE TITLE
[Umbrella][Feature] Integrate StreamPark with Sql Gateway

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#2274]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

For a better sql development experience , I want to introduce sql gateway.
Here is my proposal [StreamPark Integrate SQL Gateway](https://docs.google.com/document/d/1LVgmSPb-Rye10wunlZpOx3HqlJG2-fH5c66zhtak5vE/edit#heading=h.1im2a6ru6amz) .

Link pr https://github.com/apache/incubator-streampark/pull/2267 .

### Usage Scenario

Sql development on streampark.

### Subtasks
- [X]  Sql gateway interface and platform design done
- [X]  Implement Sql gateway interface with flink sql gateway done
- #2291
- #2889
- [X]  Workbench backend development done
- [X]  sql gateway endpoint management
- #2888
- #2890
- #2891
- #2892
- #2917 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@wolfboys @GOODBOY008 Since no one is taking this matter forward, I will try to take it forward

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
