### ISSUE TITLE
[Feature][subtask] Add implementation of backend logic for Yarn queue management feature.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2417]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add implementation of backend logic for Yarn queue management feature.

### Related issues

#2324

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
folded it into #2416
