### ISSUE TITLE
[Feature] flink cluster new status tracking

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2425]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

After discussion with the developers, it was decided that the new status function points for Flink cluster are as follows:

1. Heartbeat detection:
    a. the heartbeat detection capability of the cluster is added. Different modes (yarn-session, remote, k8s-session) have different url acquisition methods, REST polling, and status acquisition.
2. Status update: 
    a. the cluster adds a status field to record the cluster status (running, shutdown, lost).
3.  Failure alarm&failover:
    a. If cluster shutdown or lost is detected, an alarm will be sent.
    b. If the job is running on the cluster, the job will alarm in batches. At this time, it is necessary to prevent the job from alarming.
    c. The cluster does not fail over itself.
    d. The running job on the cluster will trigger the failover mechanism. At this time, you need to interrupt the failover mechanism of the job and set the job status to lost.
4. The operation logic changes:
    a. Cluster deletion: the cluster is not bound to any job, and the cluster is stopped.
    b. Cluster stop: no jobs are bound on the cluster, or all the bound jobs are not running.
    c. Job start: if the job is in remote, k8s-session, yarn-session mode, you need to check whether the cluster bound to it is running, and then you can start it. 
    d. Job addition: if it is remote, k8s-session, yarn-session mode, the cluster selection drop-down box needs to filter the cluster that is not started, leaving only the cluster that is running.
   e. Job modification: If the original mode is remote, k8s-session, yarn-session, and the bound cluster is not running, you cannot save it. You can only select another mode or switch to a running cluster.

The following is task splitting:
- [x] https://github.com/apache/incubator-streampark/issues/2421
- [x] https://github.com/apache/incubator-streampark/issues/2422
- [x] https://github.com/apache/incubator-streampark/issues/2423
- [x] https://github.com/apache/incubator-streampark/issues/2424

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Good job~ 👍

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
