### ISSUE TITLE
[Feature] [SubTask] The cluster supports remote and yarn session heartbeat monitoring

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2498]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The cluster supports remote and yarn session heartbeat monitoring and synchronous updates to the database.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment]
The following is the specific implementation logic diagram:
![未命名文件 (1)](https://user-images.githubusercontent.com/104614523/227490836-b41d7214-9b33-46cd-a9ef-96bd8c9105ba.png)
