### ISSUE TITLE
[Bug] streampark status tracking is not correct after task failed retry,and mapping is not work

### ISSUE THREAD

**Issue by yixinGod** [apache/streampark#2610]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

1.13.3

### deploy mode

yarn-application

### What happened

streampark status tracking is not correct after task failed retry，
and is always mapping mode when I execute mapping operate
<img width="666" alt="image" src="https://user-images.githubusercontent.com/19711685/231632669-773d9ada-0a6a-4729-8f1b-617cbbab8e8d.png">

the status is failed in streampark ,but in yarn the task is running 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/19711685/231632797-3aa62cc9-3e07-4002-b6f0-132c822fd2cb.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cygnusdark** [comment]
I encountered the same problem. I fixed it by manually modifying the value of state column in t_flink_app table to 5 and then make a savepoint and restore from it. This problem happened many times. Each time the restart of YARN cluster will trigger it. @wolfboys Do you have any suggestions?

**Comment by wolfboys** [comment]
> I encountered the same problem. I fixed it by manually modifying the value of state column in t_flink_app table to 5 and then make a savepoint and restore from it. This problem happened many times. Each time the restart of YARN cluster will trigger it. @wolfboys Do you have any suggestions?

You can try the latest version 2.1.0 to see if it solves the issue.

**Comment by DingPengfei** [comment]
same issue occurs in 2.1.0

**Comment by wolfboys** [comment]
fixed, (version >= 2.1.3)
