### ISSUE TITLE
[Bug] After the task status tracking is lost, remapping remains suspended

### ISSUE THREAD

**Issue by lukeyan2023** [apache/streampark#2689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-linux64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-linux64) (build 25.362-b09, mixed mode)

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14.6

Flink 环境为 高可用 StandAlone集群 

### deploy mode

remote

### What happened

After Flink task runs for a period of time, Streamark task running status tracking is lost：

![image](https://user-images.githubusercontent.com/108530647/233884618-9fac871e-4b62-4f61-af60-25408d9de27e.png)

The remapping was unsuccessful and remained in the mapping state：

![image](https://user-images.githubusercontent.com/108530647/233884730-b6dfb9bb-5bca-48da-9ffc-4168e7d628c1.png)

### Error Exception

```log
After executing remapping, the logs are as follows：


2023-04-23 17:48:15 | INFO  | XNIO-1 task-6 | org.apache.streampark.console.core.task.FlinkRESTAPIWatcher:593] FlinkRESTAPIWatcher add app to tracking,appId:10009
2023-04-23 17:52:05 | INFO  | XNIO-1 task-5 | org.apache.streampark.console.core.task.FlinkRESTAPIWatcher:593] FlinkRESTAPIWatcher add app to tracking,appId:10008
```

### Screenshots

The following is the Streamark task monitoring interface;

![image](https://user-images.githubusercontent.com/108530647/233884988-b0babffb-56c7-419d-9f14-11e7ef08ef3a.png)

Below is the running status of FLink cluster tasks：

![1682302841713](https://user-images.githubusercontent.com/108530647/233885503-b78e7d87-8366-4f9a-b482-2d8594f0c609.jpg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lukeyan2023** [comment]
Recently tested in Flink 1.17.1 standalone HA cluster environment, there is still a problem that remapping cannot be successful.

As shown below, it is always in mapping

![image](https://github.com/apache/incubator-streampark/assets/108530647/12924515-0234-4650-9c0d-9f61f9029b9f)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
