### ISSUE TITLE
[Umbrella] Refactor rest v2 api

### ISSUE THREAD

**Issue by lvshaokang** [apache/streampark#2855]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

refactor rest v2 api, api rule following this

1. https://github.com/apache/incubator-streampark/issues/2565
2. [streampark_rest_v2.yaml](https://github.com/apache/incubator-streampark/pull/2854/files#diff-089de4cb489c9dbf84c55a7f7c0512fb88713235e4cfcc61744fc8bb7778110c)

alert controller refactor example refer to [AlertConfigsApiImpl](https://github.com/apache/incubator-streampark/pull/2854/files#diff-2a0d3bd827cf2e23699fed7de979d3595fe01eeb4ef24e65ba903b96a4ebe701)

### Task list

- [x] 1. AlertController
    - [x] api define
    - [x] api refactor
    - [ ] ut
- [ ] 2. ApplicationBuildPipelineController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 3. ApplicationController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 4. ApplicationHistoryController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 5. ConfigController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 6. ExternalLinkController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 7. FlinkClusterController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 8. FlinkEnvController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 9. FlinkGateWayController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 10. FlinkPodTemplateController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 11. FlinkSqlController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 12. MessageController
    - [ ] api define
    - [ ] api refactor
    - [ ] ut
- [ ] 13. ProjectController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 14. ResourceController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 15. ProjectController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 16. SavePointController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 17. SettingController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 18. SqlWorkBenchController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 19. VariableController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 20. YarnQueueController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 21. AccessTokenController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 22. MemberController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 23. PassportController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 24. RoleController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 25. SsoController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 26. TeamController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
- [ ] 27. UserController
   - [ ] api define
   - [ ] api refactor
   - [ ] ut
 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
