### ISSUE TITLE
[Umbrella][Feature] Flink Kubernetes Module V2

### ISSUE THREAD

**Issue by Al-assad** [apache/streampark#2879]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Due to many issues with the current version of StreamPark Flink on Kubernetes in terms of submitting and tracking tasks, we hope to refactor the entire module based on the Flink Kubernetes Operator to better address the following problems:

- Inaccurate and confusing tracking of Flink on Kubernetes status;
- Unstable and lengthy Flink K8s Application Job submission process;
- Scattered Event Watcher thread pool code;

### Resources
- Design documentation: https://www.craft.me/s/LrTTzYHqSOLYqY
- Demo code: https://github.com/Al-assad/streampark-flink-kubernetes-v2

### Task list

- [x] #2880 @Al-assad 
- [x] #2881  @Al-assad
- [x] #2882 @caicancai @Al-assad 
- [x] #2883 @caicancai
- [ ] #2884 @caicancai
- [x] #2885 @ChengJie1053 @Al-assad
- [x] #2886 @Al-assad 
- [x] #2887 

### Dependency relationship of subtasks
#2880 → #2881 → #2882, #2883, #2884, #2885 → #2887

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Al-assad** [comment]
@ChengJie1053 @caicancai
Hey Bros, If you're totally stoked about tasks #2883 to #2887, they're all yours for the taking! Just claim 'em right here! 😆

**Comment by caicancai** [comment]
@Al-assad i pick #2883 and #2884

**Comment by caicancai** [comment]
> @ChengJie1053 @caicancai Hey Bros, If you're totally stoked about tasks #2883 to #2887, they're all yours for the taking! Just claim 'em right here! 😆

@Al-assad It should be #2882 to #2887，I guessed at the beginning that I wanted to pick #2882, #2883. Now I guess I can pick #2882 to #2884

**Comment by Al-assad** [comment]
> [](https://github.com/apache/incubator-streampark/issues/2884)

Sure, Looking forward to your PRs 😆

**Comment by Al-assad** [comment]
> > @ChengJie1053 @caicancai Hey Bros, If you're totally stoked about tasks #2883 to #2887, they're all yours for the taking! Just claim 'em right here! 😆
> 
> @Al-assad It should be #2882 to #2887，I guessed at the beginning that I wanted to pick #2882, #2883. Now I guess I can pick #2882 to #2884

Sure, Looking forward to your PRs 😆

**Comment by ChengJie1053** [comment]
@Al-assad i pick #2885 to #2887

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
