### ISSUE TITLE
[Umbrella] Proposal: StreamPark code-style-and-quality Improve

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2986]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

# Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

# Describe the proposal

- [Discussion & final candidate page]( https://github.com/apache/incubator-streampark/discussions/2915#discussioncomment-6793456)
- [Discussion email thread](https://lists.apache.org/thread/c3q5s8hqbnrc51vwzd4dptddvs4r930q)
- [Vote email thread](https://lists.apache.org/thread/1qvw8dqybn9vzpcv3jol72gmwbj9rfw2)

# Task list

## Overview

- [x] [Migrate & Sort out the candidate page into official website](https://github.com/apache/incubator-streampark/issues/2987). @VampireAchao
- [x] Test utils base ：Integrate test base  https://github.com/apache/incubator-streampark/issues/2896

- Using the rules to improve all files of all module.
   - Rules(mentioned in discussion page &  [website](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide) based improvement
   - Add test cases for core logic of `public methods` of classes.

## How to start ?

You can claim the tasks  whose header starts with `selection box` you are interested in.

1.  Pick the issue.
    If the task is too large, you can split it into smaller sub-tasks in sub-issues according to the situation.
2. Ping @wolfboys @RocMarshal  or other [PPMCs/committers](https://streampark.apache.org/team) on the new issue page for assignment.
3. Committers will make assignment the issue to you.
4. Then you can start to do the code work for driving the PR.

## Old tasks

- [x] org.apache.streampark.common.enums  
  https://github.com/apache/incubator-streampark/issues/2991

- [x] org.apache.streampark.console.base.config
  https://github.com/apache/incubator-streampark/issues/2992

## Tasks

1. streampark-common

   -  https://github.com/apache/incubator-streampark/issues/3044
   -  https://github.com/apache/incubator-streampark/issues/3045
   -  https://github.com/apache/incubator-streampark/issues/3046
   -  https://github.com/apache/incubator-streampark/issues/3055
   -  https://github.com/apache/incubator-streampark/issues/3056
   -  https://github.com/apache/incubator-streampark/issues/3047
   -  https://github.com/apache/incubator-streampark/issues/3057
   -  https://github.com/apache/incubator-streampark/issues/3058
   -  https://github.com/apache/incubator-streampark/issues/3059
   -  https://github.com/apache/incubator-streampark/issues/3060
   -  https://github.com/apache/incubator-streampark/issues/3061
   -  https://github.com/apache/incubator-streampark/issues/3062
   -  https://github.com/apache/incubator-streampark/issues/3063

2. streampark-console

   - [x] https://github.com/apache/incubator-streampark/issues/3064
   - [x] https://github.com/apache/incubator-streampark/issues/3065
   - [x] https://github.com/apache/incubator-streampark/issues/3066
   - [x] https://github.com/apache/incubator-streampark/issues/3067
   - [x] https://github.com/apache/incubator-streampark/issues/3068
   - [x] https://github.com/apache/incubator-streampark/issues/3069
   - [x] https://github.com/apache/incubator-streampark/issues/3070
   - [x] https://github.com/apache/incubator-streampark/issues/3071
   - [x] https://github.com/apache/incubator-streampark/issues/3072
   - [x] https://github.com/apache/incubator-streampark/issues/3073
   - [x] https://github.com/apache/incubator-streampark/issues/3074
   - [x] https://github.com/apache/incubator-streampark/issues/3075
   - [x] https://github.com/apache/incubator-streampark/issues/3076

3. streampark-flink

- [x] https://github.com/apache/incubator-streampark/issues/3077
- [x] https://github.com/apache/incubator-streampark/issues/3083
- [x] https://github.com/apache/incubator-streampark/issues/3084
- [x] https://github.com/apache/incubator-streampark/issues/3085
- [x] https://github.com/apache/incubator-streampark/issues/3086
- [x] https://github.com/apache/incubator-streampark/issues/3087
- [x] https://github.com/apache/incubator-streampark/issues/3088
- [x] https://github.com/apache/incubator-streampark/issues/3089
- [x] https://github.com/apache/incubator-streampark/issues/3090
- [x] https://github.com/apache/incubator-streampark/issues/3091
- [x] https://github.com/apache/incubator-streampark/issues/3092
- [x] https://github.com/apache/incubator-streampark/issues/3093
- [x] https://github.com/apache/incubator-streampark/issues/3094

4. streampark-spark

- [x] https://github.com/apache/incubator-streampark/issues/3095
- [x] https://github.com/apache/incubator-streampark/issues/3096
- [x] https://github.com/apache/incubator-streampark/issues/3097
- [x] https://github.com/apache/incubator-streampark/issues/3098
- [x] https://github.com/apache/incubator-streampark/issues/3099
- [x] https://github.com/apache/incubator-streampark/issues/3100
- [x] https://github.com/apache/incubator-streampark/issues/3101
- [x] https://github.com/apache/incubator-streampark/issues/3102
- [x] https://github.com/apache/incubator-streampark/issues/3103
- [x] https://github.com/apache/incubator-streampark/issues/3107
- [x] https://github.com/apache/incubator-streampark/issues/3104
- [x] https://github.com/apache/incubator-streampark/issues/3105
- [x] https://github.com/apache/incubator-streampark/issues/3106

5. streampark-test-utils

- [x] https://github.com/apache/incubator-streampark/issues/3108
- [x] https://github.com/apache/incubator-streampark/issues/3109
- [x] https://github.com/apache/incubator-streampark/issues/3110
- [x] https://github.com/apache/incubator-streampark/issues/3111
- [x] https://github.com/apache/incubator-streampark/issues/3112
- [x] https://github.com/apache/incubator-streampark/issues/3113
- [x] https://github.com/apache/incubator-streampark/issues/3114
- [x] https://github.com/apache/incubator-streampark/issues/3115
- [x] https://github.com/apache/incubator-streampark/issues/3116
- [x] https://github.com/apache/incubator-streampark/issues/3117
- [x] https://github.com/apache/incubator-streampark/issues/3118
- [x] https://github.com/apache/incubator-streampark/issues/3119
- [x] https://github.com/apache/incubator-streampark/issues/3120

## A longer-term plan is not within the scope of this optimization

-  Introduce a available docs checker plugin( like `spotless`)
-  Introduce a available commit message format checker plugin( like `pravega` repo ci)

**Comment by VampireAchao** [comment]
I am working on " Migrate & Sort out the candidate page into official website"

**Comment by wuchunfu** [comment]
@RocMarshal Please assign me the `streampark-console` module, thx.

**Comment by caicancai** [comment]
@RocMarshal @wolfboys 
Hello, I would like to ask streampark-flink-kubernetes-v2 if it is normalized now, I am not sure if there is any risk. At present, flink’s kubernetes v2 development module also involves other modules such as streampark-flink-client-api and streampark-flink-client-core. I think these modules can be ignored for now.

**Comment by wolfboys** [comment]
> @RocMarshal @wolfboys Hello, I would like to ask streampark-flink-kubernetes-v2 if it is normalized now, I am not sure if there is any risk. At present, flink’s kubernetes v2 development module also involves other modules such as streampark-flink-client-api and streampark-flink-client-core. I think these modules can be ignored for now.

👌 Okay, for this part, you just need to proceed with regular development. Other developer won't be making any improvements to these modules for now.

**Comment by caicancai** [comment]
@RocMarshal Please assign me the streampark-flink module, thx. Because this part will affect the Kubernetes_V2 code

**Comment by RocMarshal** [comment]
Thank everybody related with this first proposal !
Great work !!!
Thank all of you~. 👍 

CC @wolfboys @caicancai @GOODBOY008 @VampireAchao
