### ISSUE TITLE
Tracking issues of StreamPark 2.2.0

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3278]
This issue intends to track some features in streampark version 2.2, We plan to release this version before 2024. If you are interested in some part of this issue, please feel free to walk in and take it. Let’s make streampark to be a better project

### Feature

- [ ] 1. [pyflink support](https://github.com/apache/incubator-streampark/issues/2437)
- [x] #3280
- [ ] 3. [refactor deploy flink on k8s with flink-k8s-operator](https://github.com/apache/incubator-streampark/issues/2879)
- [x] #3281
- [ ] 5. [flink cluster state tracking](https://github.com/apache/incubator-streampark/issues/2425)
- [x] 6. [code-style-and-quality Improve](https://github.com/apache/incubator-streampark/issues/2986)
- [ ] 7. [integrate StreamPark with Sql Gateway](https://github.com/apache/incubator-streampark/issues/2274)
- [ ] 8. [job state auto-probe](https://github.com/apache/incubator-streampark/issues/3278)
- [ ] 9. [blog i18n support](https://github.com/apache/incubator-streampark/issues/3218)
- [ ] 10. [Improve k8s documentation ](https://github.com/apache/incubator-streampark/issues/3147)

**Comment by caicancai** [comment]
Improve K8S documentation

**Comment by caicancai** [comment]
https://github.com/apache/incubator-streampark/issues/3218 finsh

**Comment by caicancai** [comment]
@wolfboys Flink-Kubernetes-V2 support flink1.18
