### ISSUE TITLE
[Improve] Use isEmpty() instead of length() == 0 or size() == 0 for collections 

### ISSUE THREAD

**Issue by VampireAchao** [apache/streampark#3334]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

This rule encourages developers to adopt a more semantic and cleaner way of checking for collections. It's a small but meaningful step towards improving the overall quality of our codebase.

### Task list

- [ ] org.apache.streampark.flink.connector.doris.util.DorisDelimiterParser#parse
- [ ] org.apache.streampark.console.core.service.impl.SqlCompleteServiceImpl.SqlCompleteFstTree#getDFSWord

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ai-smalleryu** [comment]
Can you allocate it to me?

**Comment by RocMarshal** [comment]
Thanks for @VampireAchao for driving it.
Looking forward to @ai-smalleryu your contribution ~

**Comment by ai-smalleryu** [comment]
> 谢谢@VampireAchao 用于驾驶它。@ai-smalleryu你的贡献~

I only found one problem with collection judgment. It has been modified and submitted. Thank you.
