### ISSUE TITLE
[Umbrella] Track TODOs for graduation

### ISSUE THREAD

**Issue by tisonkun** [apache/streampark#3846]
The StreamPark community has run the incubator program for about two years. It grows a diverse community with a series of high-quality releases.

It's time to consider for graduating, and here is something you'd finish before that:

* [x] Update the [Incubator Status page](https://incubator.apache.org/projects/streampark.html) (You may take [OpenDAL's](https://incubator.apache.org/projects/opendal.html) as an example)
* [x] Summarize the events, public speaking, collaborations with other projects/teams, and users. All of those are not to build a fancy user wall or numbers for the market. But it indicates the project is ready for stability and being used.
* [x] Website status check. Ref [Apache Podling Website Checks](https://whimsy.apache.org/pods/).
* [x] Have an agreement on the members of the PMC
   https://lists.apache.org/thread/s3x0v50xwf9dmzr81ngkl019dvd2tpx0
   https://lists.apache.org/thread/7tk8pdh10v9c4cr56h92gw04kv049k0j
   https://lists.apache.org/thread/32mv1ctqlst0nj9sk9zhg4yz21410927
   https://lists.apache.org/thread/rggqcq6wzkd857tsrw99c50b0rj5xyz8
* [x] Go through Apache Project Maturity Model and evaluate our status
   https://streampark.apache.org/community/maturity
* [x] Ensure suitable names for project name and product names (DONE BY https://issues.apache.org/jira/browse/PODLINGNAMESEARCH-203)

Reference:

* https://incubator.apache.org/guides/graduation.html 
* https://incubator.apache.org/cookbook/#graduation_readiness_assessment

**Comment by wolfboys** [comment]
Thanks for your driving. streampark has been in incubation for almost two years. It is time for this project to graduate. [Website status check](https://whimsy.apache.org/pods/project/streampark) passed. I will update the Incubator Status page within the next two days. Other work will be discussed with PPMC members。 We hope to graduate successfully and become a TLP.

**Comment by tisonkun** [comment]
For "Have an agreement on the members of the PMC", you can start a discussion thread at dev@ or private@, and link the thread to here for recording.

**Comment by wolfboys** [comment]
> For "Have an agreement on the members of the PMC", you can start a discussion thread at dev@ or private@, and link the thread to here for recording.

Thanks for your reply. We have agreed with the PPMC members in dev@ and private@, and everyone is pleased to see the project enter the graduation process.

https://lists.apache.org/thread/s3x0v50xwf9dmzr81ngkl019dvd2tpx0
https://lists.apache.org/thread/7tk8pdh10v9c4cr56h92gw04kv049k0j
https://lists.apache.org/thread/32mv1ctqlst0nj9sk9zhg4yz21410927
https://lists.apache.org/thread/rggqcq6wzkd857tsrw99c50b0rj5xyz8

**Comment by tisonkun** [comment]
@wolfboys cool! There is still some remaining tasks listed above. Please check them and we can start a discussion on general@i.a.o then.

**Comment by wolfboys** [comment]
Regarding the StreamPark project graduation as a TLP, the community voted for the following email:

The vote thread: https://lists.apache.org/thread/ltwnwnjmych8m9b6kqjw2n08705goyfj
Result thread: https://lists.apache.org/thread/j80zj1gs6wkocy81wbn2j7ndvx0poh4t

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
