### ISSUE TITLE
StreamX 1.2.3 roadmap

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#894]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

- [x] #878 
- [x] #886
- [x] #866
- [x] #891 
- [x] #890 
- [x] #874 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
and need  to fix  this bug https://github.com/streamxhub/streamx/issues/874

**Comment by gitfortian** [comment]
and need to fix this bug https://github.com/streamxhub/streamx/issues/897
